<?= $this->doctype(); // выводим doctype: <!DOCTYPE html>



?>

   <?php 
                  
                   ?>
<html>
    <head>
        <link href="/public/img/favicon.ico" rel="shortcut icon" type="image/x-icon" />

        <?
        // выводим тег <title>
        echo $this->headTitle(); 
  
        // выводим мета-теги
        echo $this->headMeta();
         // выводим яваскрипты
        echo $this->headScript(); ?>
  	
	<script type="text/javascript" src="/public/plugins/ckeditor/ckeditor.js"></script>
       <script type="text/javascript" src="/public/js/jquery.easydrag.js"></script>
        <script type="text/javascript" src="/public/js/new.js"></script>
        <script type="text/javascript" src="/public/js/likbez.js"></script>
        

        
        <?php
       
  
        // выводим css фалы
        echo $this->headLink();
        ?>
    </head>
    <style>
        #err{
            display:inline;
            padding:5px;
            background:#ffc1c1;
            border-radius: 5px;
        }
        #wrap{
          
            height:100% !important;
            
        }
      #push{
          height:60px;
      }
      #footer {
        position:fixed;
        top:100%;
        width:100%;
        margin-top:-30px;
        height: 30px;
         margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
           background-color: #eff9ff;
           color:grey;
           opacity:0.5;
           padding-top:10px;
      }
      #footer a{
          color:lightgrey;
      }
      #footer a:hover{
          color:black;
      }
      
      .footer{
          color:grey;
          font-size:90%;
          margin-top:20px;
          padding-top:10px;
          border-top:1px solid #ddd;
      }
    
</style>


    <body>
          <div id="wrap">
        <div class="container">
          
           
            <div class="navbar">
                <? if (!empty($this->layout()->message)){ ?>
    <div class="alert <?= $this->layout()->message_class ?>">
        <a class="close" data-dismiss="alert">×</a>
        <?= $this->layout()->message ?>
    </div>
<? } ?>
                <div class="navbar-inner" >
                    <div class="container" style="width: auto">
                        <div class="pull-left" style="font-size:18px;color:white;padding-top:10px;">
                            <img src="/public/img/favicon.png" width="32" style="margin-top:-6px;" />
                            Телемедицина 
                        <?php if (isset($_SESSION['login'])){ 
                            $_SESSION['me'] = $_SESSION['login'];
                            echo " - ".$_SESSION['fio']." (".$_SESSION['login'].") - ".$_SESSION['post'];} ?></div>
                         <a href='/auth/logout' class="btn pull-right">Выход</a>&nbsp;  <a class="btn pull-right" href="/">На главную</a>
                            <br>
                       
                          
                        <div class="nav-collapse">
                            <!-- выводим главное меню -->
                            <?= $this->layout()->nav ?>
  
                            <!-- выводим форму поиска -->
                        
                         
                          
                            
                           
                        </div>
                    </div>
                </div>
            </div>
            <div class="span3">
              
                    <!-- выводим меню пользователя -->
                    <?= $this->layout()->userMenu ?>
              
            </div>
            <div class="container">
                <div class="content">
                 
                      <?= $this->layout()->content; // здесь будет автоматичеки выводиться содержимое скриптов вида?> 
                  
                   
                </div>
                <div class="footer"><?php 
                $converter = array(
        'January' => 'Январь',   'February' => 'Февраль',   'March' => 'Март', 'April' => 'Апрель',
        'May' => 'Май',   'June' => 'Июнь',   'July' => 'Июль', 'August' => 'Август',
        'September' => 'Сентябрь', 'October' => 'Октябрь', 'November' => 'Ноябрь', 'December' => 'Декабрь');
                $date =  date('F, d, Y');
                
                echo strtr($date, $converter); ?></div>
            </div>
         
            <hr/>
        </div>
           
        </div>
        <div id="push"></div>
         <div id="footer" >
             <div class="pull-right">   &copy; Телемедицина <?= date('Y') ?> [<a  href="mailto:kuznetps@gmail.com">Кузнецов П.С.</a>]
             </div>
              
            </div>
    </body>
</html>