 <script type="text/javascript" src="/public/js/g-loader.js"></script>
<div class="menu">
<div class="topmenu">  <?= $this->menu ?></div>
<div id="functions">
    <div id="inner">
    <?= $this->content ?>
        <ul id="dop" style="display:none;">
            <li>
            <textarea id="dop" class="dp" style="width:95%;height: 200px;margin-top:20px;" placeholder="Введите ваши комментарии"></textarea>
            </li>
        </ul>
    </div>

</div>

</div>

<div id="zap" style="height:100px;"></div>
<center>
    <input id="from" style="display:none;" value="<?php echo $_SESSION['login']; ?>" />


<div>
    <input type="checkbox" id="poly_check" name="poly_check"  /> <label style="display:inline;" id="lab_check" for="poly_check">Включить в отчет Шкалу оценки Полиорганной дисфункции</label>   
</div>
    <br>
    </center>

<center>
        <div id="container">
            <table><tr><td valign="top" width="200">
 <div id="send_panel">
     <textarea id="adr" style="display:none;"></textarea>

  <div id="who">
    Кому отправляем:<br>
    <select id="adresat">
       <?php 
       foreach($this->ps as $p){
           echo "<option>";
           echo $p->real_name;
           echo "</option>";
       }
       ?>
       
    </select><br>
  
</div>
<p><br>
    <a class="btn" id="byhand" style="text-shadow:none;">Ручная правка</a><a id="nohand" class="btn btn-primary" style="display:none;">Отмена</a>
     <p>
         Приложить файлы:<br>
        <div style='display:block; max-width:200px;'>
  <div id="load_ul" style="width:190px;"></div>
          <center>  <button class="lbtn" id="load_button"> </button></center><br>
         
  <div id="loading" style="display:none;"><img width="100" src="/public/img/ajax-loader.gif" alt="Loading"/> Идет загрузка...</div>            
  <div>
  <ul id="flist" style="list-style:none;">
      
  </ul>
        </div>
        </div>
     <center>
         <div>
      <button class="btn btn-primary" id="send" >Отправить</button>
      </div>
     </center>
</div> 
    <br>
 
</td>
<td>
<textarea id="otchet" name="otchet"></textarea></div>
</td>                
                </tr>
</table>
        
        <br>
            <div id="additions">
        <br>
     
        <br><hr>
        <a class="btn" id="ready">Готово</a>
    </div>

<br>
<div id="sending" style="display:none;"><img src="/public/img/ajax-loader.gif" alt="Loading"/> Идет отправка...</div> 
    </center>


<div id="push"></div>
<div style="display:none;" id="result">
    <textarea placeholder="Здесь будет отображаться результат. Выберите необходимые поля." style="font-weight: normal;">
  <?php echo $_SESSION['orgname']."<p><b>".$_SESSION['fio']."</b> - <i>".$_SESSION['post']."</i><br>"; ?> 
    </textarea>
</div>
<form id="pform" action="/card/add/" method="POST" style="display:none;">
    <input type="text" name="who"/>
    <input type="text" name="from"/>
    <input type="text" name="karts"/>
    <input type="text" name="i"/>
</form>
<div id="load_editor">
    <div id="pre">Загрузка...<br><img src="/public/img/ajax-loader.gif"> </div>
</div>
 <script type="text/javascript">
       var editing = 0;
       
       $(document).ready(function(){
           dw =  $(document).width()/2;
             CKEDITOR.replace('otchet',
    {
        // настройка тулбара
        toolbar:
        [
          //  ['Source'],
           // ['Link', 'Image'],
            ['Undo','Redo'],
            ['Bold', 'Italic', 'Underline', 'Strike', '-', 'Subscript', 'Superscript'],
            ['Find','Replace','-','SelectAll','RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'SpecialChar', '-', 'Outdent', 'Indent', 'Blockquote'],
        ],
        // настройка высоты
        height: 600,
        width: dw
       
      
    });
   
//

$(window).resize(function(){
    if (editing==1){
      $("#ok").click();  
    }
});
var old_x;
var old_y;
var old_w;
var old_h;
$("#ok").live('click',function(){
   if (editing==0){
 $("#ready").click();
   old_x =  $("#cke_otchet").offset().left;
  old_y =  $("#cke_otchet").offset().top;
  old_w =  $("#cke_otchet").width();
  old_h =  $("#cke_otchet").height();
 
  editing = 1;
  

   w = $(document).width();
   h = $(document).height();
    
   pr_x = 2/100;
   pr_y = 5/100;
   pr_w = 70/100;
   pr_w2 = 20/100
   pr_h = 40/100;
   sm_x = pr_x * w;
   sm_y = pr_y * h;
   sc_w = pr_w * w;
   sc_h = pr_h * h;
   sc_w2 = pr_w2 * w;
   $("#cke_otchet").offset({top:sm_y,left:sm_x});
   $("#send_panel").show();
   $("#send_panel").offset({top:sm_y,left:sm_x+sc_w});
   
   $("#send_panel").css('width',sc_w2);
   $("#send_panel").css('height',sc_h);
  // $("#cke_otchet").width(sc_w);
  CKEDITOR.instances.otchet.resize(sc_w,sc_h);
  CKEDITOR.instances.otchet.setReadOnly(false);
    };
});
$("#mini").click(function(){
    if (confirm("Все внесенные вами вручную изменения будут потеряны.\n Продолжить?")){
    $("#cke_otchet").offset({top:old_y,left:old_x});
      CKEDITOR.instances.otchet.resize(old_w,old_h);
  CKEDITOR.instances.otchet.setReadOnly(true);
   $("#send_panel").hide();
   editing = 0;
    }
});
       })

   
</script>  
<style>
        .lbtn{
        border:0;
        display:block;
        width:30px;
        height:30px;
        background-color: red;
        background: url('/public/img/add.png');
        cursor:pointer;
    }
    .lbtn:hover{
        
         background: url('/public/img/add_h.png');
    }
   .lbtn:active{
         background: url('/public/img/add.png');
    } 
    #load_ul #minus{
        display:inline-block;
        width:10px;
        height:10px;
        background:url('/public/img/minus.png');
        margin-right:5px;
    }
    #flist{
      padding-left:5px;
    }
    #flist a{
        font-size: 10px;
    }
   
    .menu{
        position:fixed;
        top:50px;
      
        
        
        left:50%;
        margin-left:-450px; 
      
     
    }
    .menu .topmenu{
        border:1px solid grey;
        border-radius: 10px;
        z-index:6;
        max-width:900px;
        padding:5px;
        background:url('/public/img/mbg.png') repeat-x;
    }
    .menu #functions{
    display:block;
      
    }
    .menu #functions #inner{
         display:block;
           width:300px;
    
           background: rgba(255,255,255,0.8);
       border-radius:0px 0px 10px 10px;
       margin-left:10px;
             max-height: 600px;
             overflow:auto;
       /*   border-left:1px solid grey;
         /  border-right:1px solid grey;
            border-bottom: 1px solid grey;
         */ 
           
    }
    
    .menu #functions ul li ul li a{
        color:black;
    }
  
    
    textarea{
    background:white;
    
    }
    
    #ok{
        height:20px;
        background:#0066cc;
        color:white;
        font-weight: bold;
        padding: 5px;
    }
    #cke_otchet{
    
    }
    #send_panel{
     
     
        padding:10px;
        background:lightgrey url('/public/img/grid.png');
        border:1px solid grey;
        border-radius:10px;
    }
    #ready{
        display:none;
    }
 
    .ln a{
        curor:pointer;
        
    }
    #load_editor{
      
         position: absolute;
       top:0px;
       left:0px;
       width:100%;
       height:1000%;
       background:black;
       opacity:0.8;
       z-index: 5;
    
    }
    
    #load_editor #pre{
        background-color: white;
       text-align:center;
        width:200px;
        height:50px;
         border:1px solid black;
        border-radius: 5px;
        position: fixed;
        left:50%;
        margin-left:-64px;
        top:300px;
        z-index: 7;
    }
    #moveme{
     position: absolute;
     top:0;
      width:98%;
      background:url('/public/img/k.png');
        display:block;
       
        height:10px;
        color:white;
        font-weight:bold;
        text-align: center;
        font-size: 70%;
        line-height: 110%;
        cursor: move;
        border-radius:5px 5px 0px 0px;
    }
    #moveme:hover{
       cursor: move; 
    }
    #movemo:active{
        cursor: move;
    }
    #cke_otchet{
    /*    
        position:fixed;
        top:100%;
        margin-top:-550px;
       
        left:100%;
        width:30%;
        margin-left:-30%;
     */
    }
  
    #pbar{
       width:150px;
       height:20px;
       border:1px solid grey;
       background:darkgreen;
       text-align: left;
    }
    #pr{
        background:red;
        height:20px;
        width:50%;
    }
 
    #lab_check{
             background-color:transparent;
         -webkit-transition:  background-color 0.5s linear;
     -moz-transition:  background-color  0.5s linear;
       -o-transition: background-color 0.5s linear;
       transition:  background-color  0.5s linear;  
    }
    #lab_check:hover{
        cursor:pointer;
              background-color:rgba(159,255,96,0.2);
         -webkit-transition:  background-color 0.2s linear;
     -moz-transition:  background-color  0.2s linear;
       -o-transition: background-color 0.2s linear;
       transition:  background-color  0.2s linear;
    }
    #poly_check{
        margin-top:-5px;
       
    }
    #otchet{
        width:600px;
        height: 700px;
    }
    iframe{
        border:0;
    }
    #loading {display:none;}
.error {color:#900000;}
.success {color:#009900;}

    #additions{
        display:block;
        padding:20px;
        margin-top:50px;
        text-align:center;
    }
    .topmenu a{
        margin-left:5px;
        margin-top:10px;
  
    }
    .topmenu{
      border:1px solid transparent;
    }
    .ln{
        display:block;
       
        height:25px;
        width:90%;
        padding-left:5px;
        border-radius: 5px;
           
         -webkit-transition:  background-color 0.5s linear;
     -moz-transition:  background-color  0.5s linear;
       -o-transition: background-color 0.5s linear;
       transition:  background-color  0.5s linear;
    }
    .ln:hover{
          background-color:rgba(159,255,96,0.2);
         -webkit-transition:  background-color 0.2s linear;
     -moz-transition:  background-color  0.2s linear;
       -o-transition: background-color 0.2s linear;
       transition:  background-color  0.2s linear;
    }
    ul {
        list-style: none;
    }
    ul li{
        margin-left:-20px;
        margin-top:0px;
        
    }
    ul li ul{
        list-style-image:url('/public/img/list.png');
        list-style-position:  outside;
    }
    ul li ul li{
        margin-left:10px;
    }
    ul li ul li a{
        display:block;
        width:90%;
        color:black;
        font-weight:bold;
        padding-left:5px;
         background-color:rgba(255,255,255,0.1);
         -webkit-transition:  background-color 0.5s linear;
     -moz-transition:  background-color  0.5s linear;
       -o-transition: background-color 0.5s linear;
       transition:  background-color  0.5s linear;
    }
    ul li ul li a:hover{
       background-color:rgba(255,96,96,0.2);
         -webkit-transition:  background-color 0.2s linear;
     -moz-transition:  background-color  0.2s linear;
       -o-transition: background-color 0.2s linear;
       transition:  background-color  0.2s linear;
    }
    #functions{
     
        display:block;
      
    }
    #result{
        position: fixed;
        height:280px;
        width:600px;
        left:50%;
        margin-left: -300px;
        opacity:0.7;
        overflow: hidden;
         border-radius: 10px 10px 0px 0px;
         border: 2px solid #81caf8;
         top:100%;
         margin-top:-320px;
    }
    #result textarea{
        resize:none;
         border-radius: 10px 10px 0px 0px;
        width:587px;
        min-height: 270px;
    }   
    #push{
        height:400px;
        width:100%;
    }
    #anamnesis{
        margin-top:20px;
       
       width:95%;
        height: 200px;
        border-radius: 5px;
       position:relative;
       top:0%;
       
       
    }
    

  
    
</style>
<textarea id="kart" style="display:none;"></textarea>
