<div class="topmenu">  <?= $this->menu ?></div>
<div id="functions">

    <?= $this->content ?>
    

</div>
    <div id="additions">
        <div style='display:block;text-align:left;position:relative;width:300px;margin-left:-150px;left:50%;'>
            Дополнительная информация:
            <br>
            <textarea id="dop" style="width:100%;"></textarea>
        </div><br>
          <div style='display:block;position:relative;width:300px;margin-left:-150px;left:50%;'>
          
              
            
              <iframe id="fr" src="/frames/123.html" width="300" height="160" hspace="10" vspace="10" align="center" >
Ваш браузер не поддерживает плавающие фреймы!
</iframe> 
  <div id="loading" style="display:none;"><img src="/img/ajax-loader.gif" alt="Loading"/> Идет загрузка...</div>            
              
        </div>
        <br><hr>
        <a class="btn" id="ready">Готово</a>
    </div>
<div id="otchet"></div>
<center><button class="btn btn-primary" id="send" style="display:none;opacity:0.0;">Отправить</button></center>
<div id="push"></div>
<div style="display:none;" id="result">
    <textarea placeholder="Здесь будет отображаться результат. Выберите необходимые поля." style="font-weight: normal;">
  <?php echo $_SESSION['orgname']."<p>".$_SESSION['fio']."<p>".$_SESSION['post']."<p>"; ?> 
    </textarea>
</div>


<style>
    iframe{
        border:0;
    }
    #loading {display:none;}
.error {color:#900000;}
.success {color:#009900;}

    #additions{
        display:block;
        padding:20px;
        margin-top:50px;
        text-align:center;
    }
    .topmenu a{
        margin-left:5px;
        margin-top:10px;
  
    }
    .topmenu{
      border:1px solid transparent;
    }
    .ln{
        display:block;
       
        height:25px;
        width:100%;
        padding-left:5px;
        border-radius: 5px;
    }
    .ln:hover{
        background:url('/img/li.png');
    }
    ul {
        list-style: none;
    }
    ul li{
        margin-left:-20px;
        margin-top:0px;
        
    }
    ul li ul li{
        margin-left:10px;
    }
    ul li ul li a{
        display:block;
        width:100%;
        color:black;
        font-weight:bold;
        padding-left:5px;
    }
    ul li ul li a:hover{
        background:url('/img/li_red.png');
    }
    #functions{
     
        display:block;
      
    }
    #result{
        position: fixed;
        height:280px;
        width:600px;
        left:50%;
        margin-left: -300px;
        opacity:0.7;
        overflow: hidden;
         border-radius: 10px 10px 0px 0px;
         border: 2px solid #81caf8;
         top:100%;
         margin-top:-320px;
    }
    #result textarea{
        resize:none;
         border-radius: 10px 10px 0px 0px;
        width:587px;
        min-height: 270px;
    }   
    #push{
        height:300px;
        width:100%;
    }
    #anamnesis{
        margin-top:20px;
        margin-left:40px;
        width:300px;
        height: 200px;
        border-radius: 5px;
       position:relative;
       top:0%;
       
       
    }
    

  
    
</style>
<script>
    
 $(document).ready(function(){
     $('#comps').click(function(){
         $('ul#comps').slideToggle(500); 
         if ($(this).attr('onme')=='1'){
             $(this).attr('onme','0');
             $(this).css('font-weight','normal');
         }else {
             $(this).attr('onme','1');
             $(this).css('font-weight','bold');
         }
     });
     $(".ln").click(function(){
         $(this).next().slideToggle(500); 
     });
     $("#anamnesis").change(function(){
        $(this).css('color','darkgreen'); 
        $(this).attr('changed','1');
        
         $(this).css('text-shadow',' 0px 0px 2px blue'); 
     
    

    
     });
      $("#anam").click(function(){
         $("#anamnesis").slideToggle(500); 
         if ($(this).attr('onme')=='1'){
             $(this).attr('onme','0');
             $(this).css('font-weight','normal');
         }else {
             $(this).attr('onme','1');
             $(this).css('font-weight','bold');
         }
     });
     $("ul li ul li a").click(function(){
       if ($(this).attr('class')=='0'){
           $(this).attr('class','1');
           $(this).css('color','green');
       }else {
            $(this).attr('class','0');
           $(this).css('color','');
       }
     });
        $('#obj').click(function(){
         $('ul#obj_ul').slideToggle(500); 
         if ($(this).attr('onme')=='1'){
             $(this).attr('onme','0');
             $(this).css('font-weight','normal');
         }else {
             $(this).attr('onme','1');
             $(this).css('font-weight','bold');
         }
     });
      $('#neuro').click(function(){
         $('ul#neuro').slideToggle(500); 
         if ($(this).attr('onme')=='1'){
             $(this).attr('onme','0');
             $(this).css('font-weight','normal');
         }else {
             $(this).attr('onme','1');
             $(this).css('font-weight','bold');
         }
     });
     $("#ready").click(function(){
       res = "<div style='padding:5px;border:1px solid grey;'>"+$("#result textarea").val();
       res += "</div><p>";
       
        i=0;
        r = '';
        $("ul#comps a.1").each(function(){
            i++;
            r+= '- '+$(this).html()+"<br>";
        });
        if (i>0) res+="</b><b>Пациент поступил с жалобами на:</b><br>"+r;
        res += "<p>"; 
        if ($("#anamnesis").attr('changed')=='1'){
            res+="<b>Анамнез:</b><br>";
            res+=$("#anamnesis").val();
            res+="<br>";
             res += "<p>"; 
        }
        
        
        
        i=0;
        r = '';
        $("ul#obj_ul a.1").each(function(){
            i++;
            r+=$(this).attr('title')+': '+$(this).html()+"<br>";
        });
         if (i>0) res+="<b>Объективно:</b> <br>"+r;
        res += "<p>"; 
        
         i=0;
        r = '';
        $("ul#neuro a.1").each(function(){
            i++;
            r+=$(this).attr('title')+': '+$(this).html()+"<br>";
        });
         if (i>0) res+="<b>Невростатус:</b> <br>"+r;
        res += "<p>"; 
        
       if($("#dop").val()!='')
        res+="<b>Дополнитеьная информация:</b> <br>"+$("#dop").val()+"<p>";
        
         var iFrameDOM = $("#fr").contents();
   //Теперь мы можем использовать find() для доступа к элементам iframe:
   //например
   s = iFrameDOM.find("#fnamebox").html();
   if (s!=undefined){
       if (s.length>0){
   res+='<hr> Прилагаемые файлы:<br>';
   
   m = s.split('|');
   i = m.length;
   for(i=1;i<=m.length-1;i++)
       if(m[i].substring(m[i].lastIndexOf('.')+1,m[i].length).toLowerCase()=='pdf'){
     res+= "<br><a target=_blank href='/upload_pdf/"+m[i]+"'><img width='32' src='/img/pdf.ico' />"+m[i]+"</a><br>";

 }else if(m[i].substring(m[i].lastIndexOf('.')+1,m[i].length).toLowerCase()=='PDF'){
      res+= "<br><a target=_blank href='/upload_pdf/"+m[i]+"'><img width='32' src='/img/pdf.ico' />"+m[i]+"</a><br>";
}else 
     res+= "<br><img width='32' src='/upload/"+m[i]+"_thumb.jpg' /><a onclick='$(this).next().slideToggle(500);'>"+m[i]+"</a><div style='display:none;font-size:70%;'> Нажмите на картинку,чтобы скачать<br><a href='/upload/"+m[i]+".jpg'><img title='Скачать' src='/upload/"+m[i]+".jpg'/></a></div><br>";
   }


}




        $("#otchet").html(res);
        $("#send").show();
        $("#send").animate({'opacity':1.0},500);
     });
    
     
     
 })
 
</script>